import { BackupConfiguration } from '../../../apps/main/background-processes/backups/BackupConfiguration/BackupConfiguration';
import { BackupErrorsTracker } from './backup-errors-tracker';
import { BackupsProcessStatus } from '../../../apps/main/background-processes/backups/BackupsProcessStatus/BackupsProcessStatus';
import { BackupProgressTracker } from './backup-progress-tracker';
import { BackupManager } from './backup-manager';
export const BACKUP_MANUAL_INTERVAL = -1;
export const backupsConfig = new BackupConfiguration();
export const tracker = new BackupProgressTracker();
export const backupErrorsTracker = new BackupErrorsTracker();
export const status = new BackupsProcessStatus('STANDBY');
export const backupManager = new BackupManager(status, tracker, backupErrorsTracker, backupsConfig);
