import { CleanerContext, CLEANER_SECTION_KEYS, CleanerSectionKey } from '@internxt/drive-desktop-core/build/backend/features/cleaner/types/cleaner.types';
import { SectionConfig } from '@internxt/drive-desktop-core/build/frontend/features/cleaner/cleaner.types';
import { WindowsCleanerReport } from './cleaner.types';

export const cleanerSectionKeys: CleanerSectionKey<WindowsCleanerReport>[] = [...CLEANER_SECTION_KEYS, 'windowsSpecific'];

export const sectionConfig: SectionConfig = {
  appCache: { name: 'App Cache', color: '#3B82F6' },
  logFiles: { name: 'Log Files', color: '#10B981' },
  trash: { name: 'Trash', color: '#F59E0B' },
  webStorage: { name: 'Web Storage', color: '#EF4444' },
  webCache: { name: 'Web Cache', color: '#8B5CF6' },
  windowsSpecific: { name: 'Windows Specific', color: '#69ed28ff' },
};

export const cleanerCtx: CleanerContext = {
  browser: {
    criticalExtensions: [
      '.exe',
      '.dll',
      '.sys',
      '.ini',
      '.bat',
      '.cmd',
      '.json',
      '.sqlite',
      '.sqlite3',
      '.db',
      '.ldb',
      '.pref',
      '.cfg',
      '.conf',
      '.p12',
      '.pfx',
      '.crt',
      '.cer',
      '.key',
      '.crx',
      '.xpi',
      '.nex',
      '.bin',
    ],
    criticalFilenames: [
      'lock',
      'log',
      'manifest-000001',
      'current',
      'log.old',
      'preferences',
      'secure preferences',
      'local state',
      'web data',
      'login data',
      'history',
      'bookmarks',
      'favicons',
      'top sites',
      'shortcuts',
      'visited links',
      'extension cookies',
      'extension state',
      'prefs.js',
      'user.js',
      'userChrome.css',
      'userContent.css',
      'protected storage',
      'transportsecurity',
      'manifest.json',
      'background.js',
      'content_script.js',
      'extensions',
      'external extensions',
      'user scripts',
    ],
  },
  appCache: {
    criticalExtensions: [
      '.exe',
      '.dll',
      '.sys',
      '.msi',
      '.bat',
      '.cmd',
      '.json',
      '.db',
      '.xml',
    ],
    criticalKeywords: [
      'config',
      'settings',
      'manifest',
      'registry',
      'profile',
    ],
  },
  logFiles: {
    safeExtensions: ['.log', '.txt', '.out'],
  },
};
