#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
# TODO PB-4229: Fix the pre-commit hook
# Commented out to avoid blocking the commit, uncomment when ticket above is resolved
#npx yarn run lint
#npx yarn run type-check
