name: Build release

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pull_request:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'

      - name: Create .npmrc file
        run: |
          touch .npmrc
          echo "@internxt:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }}" >> .npmrc
          echo "always-auth=true" >> .npmrc

      - name: Create .env file
        run: |
          cat <<EOF > .env
          BRIDGE_URL="${{ secrets.BRIDGE_URL }}"
          CRYPTO_KEY="${{ secrets.CRYPTO_KEY }}"
          DESKTOP_HEADER="${{ secrets.DESKTOP_HEADER }}"
          DRIVE_URL="${{ secrets.DRIVE_URL }}"
          NEW_CRYPTO_KEY="${{ secrets.NEW_CRYPTO_KEY }}"
          NOTIFICATIONS_URL="${{ secrets.NOTIFICATIONS_URL }}"
          PAYMENTS_URL="${{ secrets.PAYMENTS_URL }}"
          PORT=${{ secrets.PORT }}
          EOF

      - name: Print .env file
        run: cat .env

      - name: Install dependencies
        run: npm run init:ci

      - name: Create package
        run: npm run package
