name: Build release

on:
  workflow_dispatch:

jobs:
  build_release:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup clamAV
        run: release\clamAV.ps1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env file
        env:
          ANALYZE: ${{ secrets.ANALYZE }}
          BRIDGE_URL: ${{ secrets.BRIDGE_URL }}
          CRYPTO_KEY: ${{ secrets.CRYPTO_KEY }}
          DESKTOP_HEADER: ${{ secrets.DESKTOP_HEADER }}
          DRIVE_URL: ${{ secrets.DRIVE_URL }}
          NEW_CRYPTO_KEY: ${{ secrets.NEW_CRYPTO_KEY }}
          NOTIFICATIONS_URL: ${{ secrets.NOTIFICATIONS_URL }}
          PAYMENTS_URL: ${{ secrets.PAYMENTS_URL }}
          PORT: ${{ secrets.PORT }}
          SM_API_KEY: ${{ secrets.SM_API_KEY }}
          SM_CLIENT_CERT_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
          SM_CLIENT_CERT_FILE_B64: ${{ secrets.SM_CLIENT_CERT_FILE_B64 }}
        run: |
          echo "ANALYZE=$ANALYZE" > .env
          echo "BRIDGE_URL=$BRIDGE_URL" >> .env
          echo "CRYPTO_KEY=$CRYPTO_KEY" >> .env
          echo "DESKTOP_HEADER=$DESKTOP_HEADER" >> .env
          echo "DRIVE_URL=$DRIVE_URL" >> .env
          echo "NEW_CRYPTO_KEY=$NEW_CRYPTO_KEY" >> .env
          echo "NOTIFICATIONS_URL=$NOTIFICATIONS_URL" >> .env
          echo "PAYMENTS_URL=$PAYMENTS_URL" >> .env
          echo "PORT=$PORT" >> .env
          echo "SM_API_KEY=$SM_API_KEY" >> .env
          echo "SM_CLIENT_CERT_PASSWORD=$SM_CLIENT_CERT_PASSWORD" >> .env
          echo "SM_CLIENT_CERT_FILE_B64=$SM_CLIENT_CERT_FILE_B64" >> .env

      - name: Install dependencies
        run: npm run init:ci

      - name: Create package
        run: npm run package

      - name: Code signing with Software Trust Manager
        uses: digicert/ssm-code-signing@9476ceec3ea1c63298d4403b983e1ccf2556ff4c #v1.1.0

      - name: Sign build
        run: release\sign.ps1

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: signed-windows-build
          path: |
            build/Internxt-Setup-*.exe
            build/Internxt-Setup-*.exe.blockmap
            build/latest.yml
