name: Build release

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pull_request:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm run init:ci

      - name: Create package
        run: npm run package
