name: Golang Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: 🐹 Golang Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: packages/fuse-daemon/go.mod

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.11.4
          working-directory: packages/fuse-daemon
