name: Pull request checks

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    environment:
      name: development

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      # You cannot read packages from other private repos with GITHUB_TOKEN
      # You have to use a PAT instead https://github.com/actions/setup-node/issues/49
      - run: echo "@internxt:registry=https://npm.pkg.github.com" >> .npmrc
      - run: echo "registry=https://registry.yarnpkg.com/" > .npmrc
      - run: echo //npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }} >> .npmrc
      - run: echo "always-auth=true" >> .npmrc

      - name: Install dependencies
        run: yarn --ignore-scripts

      - name: Run Prettier
        run: yarn prettier src --check
