name: Pull request checks

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR size
      - uses: maidsafe/pr_size_checker@v2
        with:
          max_lines_changed: 500
